query getPolls($limit: Int, $order: String, $where: JSON, $offset: Int){
	polls(limit: $limit, order: $order, where: $where, offset: $offset) {
  	id
    userId
    prompt
  }
}

mutation createPoll($input: PollInput!) {
  createPoll(input: $input) {
    id
    userId
    published
  }
}

query getPoll($id: UUID!) {
  poll(id: $id) {
		id
    prompt
    published
    pollOptions {
      id
			option
      userSelections {
        id
      }
    }
  }
}
