/* eslint-disable react/prop-types, react/jsx-props-no-spreading */
import { config } from '@fortawesome/fontawesome-svg-core';
import Head from 'next/head';
import { SessionProvider } from 'next-auth/react';
import { ApolloProvider } from '@apollo/client';

import '@fortawesome/fontawesome-svg-core/styles.css';
import '../styles/globals.css';

import client from '../lib/apolloClient';
import ErrorBoundary from '../lib/components/ErrorBoundary';

config.autoAddCss = false;

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={pageProps.session}>
        <ApolloProvider client={client}>
          <ErrorBoundary>
            <Component {...pageProps} />
          </ErrorBoundary>
        </ApolloProvider>
      </SessionProvider>
    </>
  );
}

export default App;
