/* eslint-disable react/jsx-filename-extension */
import Head from 'next/head';
import Layout from '../lib/components/Layout';
import PollList from '../lib/components/PollList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Qik Poll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="p-3">
          <PollList />
        </div>
      </Layout>
    </>
  );
}
